from paladeenz import db
from flask_login import UserMixin
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True)
    password_hash = db.Column(db.String(128))
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.String(30))
    player_rank = db.Column(db.Integer)
    

class Match(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    match_id = db.Column(db.String(30))
    match_time = db.Column(db.String(30))
    match_map = db.Column(db.String(30))
    match_score = db.Column(db.String(30))

    player_one_name = db.Column(db.String(30))
    player_one_item1 = db.Column(db.String(30))
    player_one_item2 = db.Column(db.String(30))
    player_one_item3 = db.Column(db.String(30))
    player_one_item4 = db.Column(db.String(30))
    player_one_item1_level = db.Column(db.Integer)
    player_one_item2_level = db.Column(db.Integer)
    player_one_item3_level = db.Column(db.Integer)
    player_one_item4_level = db.Column(db.Integer)
    player_one_team = db.Column(db.String(30))
    player_one_rank = db.Column(db.Integer)
    player_one_kda = db.Column(db.String(30))

    player_two_name = db.Column(db.String(30))
    player_two_item1 = db.Column(db.String(30))
    player_two_item2 = db.Column(db.String(30))
    player_two_item3 = db.Column(db.String(30))
    player_two_item4 = db.Column(db.String(30))
    player_two_item1_level = db.Column(db.Integer)
    player_two_item2_level = db.Column(db.Integer)
    player_two_item3_level = db.Column(db.Integer)
    player_two_item4_level = db.Column(db.Integer)
    player_two_team = db.Column(db.String(30))
    player_two_rank = db.Column(db.Integer)
    player_two_kda = db.Column(db.String(30))

    player_three_name = db.Column(db.String(30))
    player_three_item1 = db.Column(db.String(30))
    player_three_item2 = db.Column(db.String(30))
    player_three_item3 = db.Column(db.String(30))
    player_three_item4 = db.Column(db.String(30))
    player_three_item1_level = db.Column(db.Integer)
    player_three_item2_level = db.Column(db.Integer)
    player_three_item3_level = db.Column(db.Integer)
    player_three_item4_level = db.Column(db.Integer)
    player_three_team = db.Column(db.String(30))
    player_three_rank = db.Column(db.Integer)
    player_three_kda = db.Column(db.String(30))

    player_four_name = db.Column(db.String(30))
    player_four_item1 = db.Column(db.String(30))
    player_four_item2 = db.Column(db.String(30))
    player_four_item3 = db.Column(db.String(30))
    player_four_item4 = db.Column(db.String(30))
    player_four_item1_level = db.Column(db.Integer)
    player_four_item2_level = db.Column(db.Integer)
    player_four_item3_level = db.Column(db.Integer)
    player_four_item4_level = db.Column(db.Integer)
    player_four_team = db.Column(db.String(30))
    player_four_rank = db.Column(db.Integer)
    player_four_kda = db.Column(db.String(30))

    player_five_name = db.Column(db.String(30))
    player_five_item1 = db.Column(db.String(30))
    player_five_item2 = db.Column(db.String(30))
    player_five_item3 = db.Column(db.String(30))
    player_five_item4 = db.Column(db.String(30))
    player_five_item1_level = db.Column(db.Integer)
    player_five_item2_level = db.Column(db.Integer)
    player_five_item3_level = db.Column(db.Integer)
    player_five_item4_level = db.Column(db.Integer)
    player_five_team = db.Column(db.String(30))
    player_five_rank = db.Column(db.Integer)
    player_five_kda = db.Column(db.String(30))

    player_six_name = db.Column(db.String(30))
    player_six_item1 = db.Column(db.String(30))
    player_six_item2 = db.Column(db.String(30))
    player_six_item3 = db.Column(db.String(30))
    player_six_item4 = db.Column(db.String(30))
    player_six_item1_level = db.Column(db.Integer)
    player_six_item2_level = db.Column(db.Integer)
    player_six_item3_level = db.Column(db.Integer)
    player_six_item4_level = db.Column(db.Integer)
    player_six_team = db.Column(db.String(30))
    player_six_rank = db.Column(db.Integer)
    player_six_kda = db.Column(db.String(30))

    player_seven_name = db.Column(db.String(30))
    player_seven_item1 = db.Column(db.String(30))
    player_seven_item2 = db.Column(db.String(30))
    player_seven_item3 = db.Column(db.String(30))
    player_seven_item4 = db.Column(db.String(30))
    player_seven_item1_level = db.Column(db.Integer)
    player_seven_item2_level = db.Column(db.Integer)
    player_seven_item3_level = db.Column(db.Integer)
    player_seven_item4_level = db.Column(db.Integer)
    player_seven_team = db.Column(db.String(30))
    player_seven_rank = db.Column(db.Integer)
    player_seven_kda = db.Column(db.String(30))

    player_eight_name = db.Column(db.String(30))
    player_eight_item1 = db.Column(db.String(30))
    player_eight_item2 = db.Column(db.String(30))
    player_eight_item3 = db.Column(db.String(30))
    player_eight_item4 = db.Column(db.String(30))
    player_eight_item1_level = db.Column(db.Integer)
    player_eight_item2_level = db.Column(db.Integer)
    player_eight_item3_level = db.Column(db.Integer)
    player_eight_item4_level = db.Column(db.Integer)
    player_eight_team = db.Column(db.String(30))
    player_eight_rank = db.Column(db.Integer)
    player_eight_kda = db.Column(db.String(30))

    player_nine_name = db.Column(db.String(30))
    player_nine_item1 = db.Column(db.String(30))
    player_nine_item2 = db.Column(db.String(30))
    player_nine_item3 = db.Column(db.String(30))
    player_nine_item4 = db.Column(db.String(30))
    player_nine_item1_level = db.Column(db.Integer)
    player_nine_item2_level = db.Column(db.Integer)
    player_nine_item3_level = db.Column(db.Integer)
    player_nine_item4_level = db.Column(db.Integer)
    player_nine_team = db.Column(db.String(30))
    player_nine_rank = db.Column(db.Integer)
    player_nine_kda = db.Column(db.String(30))

    player_ten_name = db.Column(db.String(30))
    player_ten_item1 = db.Column(db.String(30))
    player_ten_item2 = db.Column(db.String(30))
    player_ten_item3 = db.Column(db.String(30))
    player_ten_item4 = db.Column(db.String(30))
    player_ten_item1_level = db.Column(db.Integer)
    player_ten_item2_level = db.Column(db.Integer)
    player_ten_item3_level = db.Column(db.Integer)
    player_ten_item4_level = db.Column(db.Integer)
    player_ten_team = db.Column(db.String(30))
    player_ten_rank = db.Column(db.Integer)
    player_ten_kda = db.Column(db.String(30))

class LoginForm(FlaskForm):
    username = StringField('username')
    password = PasswordField('password')
    submit = SubmitField('Submit')